
using System;
using System.ComponentModel;

namespace Core.DTO.Master
{
    public class FaculModel
    {
        public string FacCode { get; set; }
        public string FacUsid { get; set; }
        public string FacUsidUpd { get; set; }
        public int? FacOfrNo { get; set; }
        public string FacType { get; set; }
        public string FacSubType { get; set; }
        public string FacUwriter { get; set; }
        public string FacUwriterName { get; set; }
        public string FacMkter { get; set; }
        public string FacMkterName { get; set; }
        public string FacOldCode { get; set; }
        public string FacCoinCode { get; set; }
        public string FacMraCode { get; set; }
        public string FacOpnCover { get; set; }
        public DateTime? FacOfrDate { get; set; }
        public DateTime? FacRepDate { get; set; }
        public DateTime? FacComDate { get; set; }
        public DateTime? FacExpDate { get; set; }
        public DateTime? FacHoldCvrDate { get; set; }
        public DateTime? FacInpDate { get; set; }
        public DateTime? FacUpdDate { get; set; }
        public string FacCedant { get; set; }
        public string FacBroker { get; set; }
        public string FacOccupation { get; set; }
        public string FacOldRef { get; set; }
        public string FacCcRef { get; set; }
        public string FacPolicyNo { get; set; }
        public string FacSource { get; set; }
        public string FacConstrClass { get; set; }
        public string FacMainClass { get; set; }
        public string FacSubClass { get; set; }
        public string FacSterr { get; set; }
        public string FacCurrency { get; set; }
        public string FacRiPrd { get; set; }
        public string FacAccSts { get; set; }
        public string FacRnSts { get; set; }
        public string FacRnFlag { get; set; }
        public string FacInsured { get; set; }
        public string FacRisk { get; set; }
        public string FacCover { get; set; }
        public string FacDesc { get; set; }
        public string FacPremRate { get; set; }
        public string FacCommRate { get; set; }
        public decimal? FacPremPer { get; set; }
        public decimal? FacComm { get; set; }
        public decimal? FacComm1 { get; set; }
        public decimal? FacComm2 { get; set; }
        public decimal? FacComm3 { get; set; }
        public decimal? FacComm4 { get; set; }
        public string FacGnSts { get; set; }
        public decimal? FacOthDeduct { get; set; }
        public decimal? FacWrtShr { get; set; }
        public decimal? FacSndShr { get; set; }
        public decimal? FacTotsi { get; set; }
        public decimal? FacTargetSi { get; set; }
        public decimal? FacPmlPer { get; set; }
        public decimal? FacCcsi { get; set; }
        public decimal? FacCcRetn { get; set; }
        public decimal? FacOursi { get; set; }
        public decimal? FacGpremium { get; set; }
        public decimal? FacNpremium { get; set; }
        public decimal? FacDeductible { get; set; }
        public decimal? FacIndemnity { get; set; }
        public decimal? FacMinPrem { get; set; }
        public decimal? FacDepPrem { get; set; }
        public string FacOutTty1 { get; set; }
        public decimal? FacOutPrc1 { get; set; }
        public decimal? FacOutAmt1 { get; set; }
        public string FacOutTty2 { get; set; }
        public decimal? FacOutPrc2 { get; set; }
        public decimal? FacOutAmt2 { get; set; }
        public string FacOutTty3 { get; set; }
        public decimal? FacOutPrc3 { get; set; }
        public decimal? FacOutAmt3 { get; set; }
        public string FacOutTty4 { get; set; }
        public decimal? FacOutPrc4 { get; set; }
        public decimal? FacOutAmt4 { get; set; }
        public string FacOutTty5 { get; set; }
        public decimal? FacOutPrc5 { get; set; }
        public decimal? FacOutAmt5 { get; set; }
        public string FacOutFac { get; set; }
        public decimal? FacOutFacPrc { get; set; }
        public decimal? FacOutFacAmt { get; set; }
        public decimal? FacOurPrc { get; set; }
        public decimal? FacOurAmt { get; set; }
        public string FacNpTrt { get; set; }
        public string FacOutPrsts { get; set; }
        public string FacInfo { get; set; }
        public string FacBis { get; set; }
        public string FacStsSlip { get; set; }
        public DateTime? FacDueDate1 { get; set; }
        public DateTime? FacDueDate2 { get; set; }
        public DateTime? FacDueDate3 { get; set; }
        public DateTime? FacDueDate4 { get; set; }
        public DateTime? FacDueDate5 { get; set; }
        public DateTime? FacDueDate6 { get; set; }
        public DateTime? FacDueDate7 { get; set; }
        public DateTime? FacDueDate8 { get; set; }
        public DateTime? FacDueDate9 { get; set; }
        public DateTime? FacDueDate10 { get; set; }
        public string FacVessel { get; set; }
        public string FacClassifi { get; set; }
        public string FacCHull { get; set; }
        public string FacConstr { get; set; }
        public string FacOld { get; set; }
        public string FacTonage { get; set; }
        public string FacTerritory { get; set; }
        public string FacCargo { get; set; }
        public string FacCCargo { get; set; }
        public string FacMjenis { get; set; }
        public string FacMkondisi { get; set; }
        public string FacMwilayah { get; set; }
        public string FacMusia { get; set; }
        public string FacSlip { get; set; }
        public decimal? FacAdjAmt { get; set; }
        public string FacAdjSts { get; set; }
        public string FacHull { get; set; }
        public string FacHeavy { get; set; }
        public int? FacRiskNo { get; set; }
        public string FacPostal { get; set; }
        public string FacAdmin { get; set; }
        public string FacAdminName { get; set; }
        public string FacCoycode { get; set; }
        public DateTime? FacDueDate11 { get; set; }
        public DateTime? FacDueDate12 { get; set; }
        public string FacUwcedingName { get; set; }
        public int? FacInsuredCode { get; set; }

        public UwriterModel MasterUwriter { get; set; }
        public SubtypeModel MasterSubtype { get; set; }
    }
    
}
