//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientViewIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KTPH_PatAdmission
    {
        public string CaseID { get; set; }
        public string SAPPaientID { get; set; }
        public string WardClass { get; set; }
        public Nullable<System.DateTime> MovementDateTime { get; set; }
        public string OrganizationalUnit { get; set; }
        public string Bed { get; set; }
        public string PatientClass { get; set; }
        public string AttendingDoctor { get; set; }
        public string Institution { get; set; }
        public string CaseType { get; set; }
        public string Department { get; set; }
        public string Room { get; set; }
        public string SequenceNumber { get; set; }
        public string MovementCategory { get; set; }
        public Nullable<System.Guid> InternalPatientID { get; set; }
        public string AdmittingDoctor { get; set; }
        public string PlannedIndicator { get; set; }
        public string EmergencyIndicator { get; set; }
        public string AccidentType { get; set; }
        public string AccidentNumber { get; set; }
        public string ExternalHospital { get; set; }
        public string AdmittingDepartment { get; set; }
        public string DischargeDisposition { get; set; }
        public string MovementCreateUser { get; set; }
        public string MovementCancelIndicator { get; set; }
        public string MovementCancelUser { get; set; }
        public string MovementReason1 { get; set; }
        public string MovementReason2 { get; set; }
        public string PhysicianSpecialty { get; set; }
        public string ModeOfArrival { get; set; }
        public string DischargeDoctor { get; set; }
        public string ReferingDoctor { get; set; }
        public string MovementType { get; set; }
        public string TreatmentCategory { get; set; }
        public string BillingIndicator { get; set; }
        public string CheckDigit { get; set; }
        public string CaseCreateUser { get; set; }
        public string CaseUpdateUser { get; set; }
        public string CaseCancelIndicator { get; set; }
        public string CaseCancelUser { get; set; }
        public string Specialty { get; set; }
        public string CaseEndType { get; set; }
        public string MovementUpdateUser { get; set; }
    }
}
