//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientViewIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PatientMasterInfo
    {
        public System.Guid InternalPatientID { get; set; }
        public string SAPPatientID { get; set; }
        public string Sex { get; set; }
        public string PatientName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string IdentificationDocNo { get; set; }
        public string ExternalPatientID { get; set; }
        public string Insitution { get; set; }
    }
}
